version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/hermes"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/telegram-user-info-bot"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/hermes/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/hermes/vscode-server"
    schedule:
      interval: "weekly"
