apiVersion: 1

datasources:
  - name: Hermes Prometheus
    uid: hermes-prometheus
    type: prometheus
    access: proxy
    url: http://@PROMETHEUS_BIND_ADDRESS@:@PROMETHEUS_PORT@
    isDefault: true
    editable: false
