[Service]
EnvironmentFile=/etc/hermes-grafana.env
Environment=GF_SERVER_HTTP_ADDR=@GRAFANA_BIND_ADDRESS@
Environment=GF_SERVER_HTTP_PORT=@GRAFANA_PORT@
Environment=GF_AUTH_ANONYMOUS_ENABLED=false
Environment=GF_USERS_ALLOW_SIGN_UP=false
